config/routes.rb
Rails.application.routes.draw do
  root "flow#start"

  get "start", to: "flow#start", as: "start"
  get "eligibility", to: "flow#eligibility", as: "eligibility"
  post "eligibility", to: "flow#check_eligibility"
  get "eligible", to: "flow#eligible", as: "eligible"
  get "ineligible", to: "flow#ineligible", as: "ineligible"
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  resources :employees, except: :edit

  post "finish", to: "flow#finish", as: "finish"
  post "logout", to: "sessions#destroy", as: "logout" 

  namespace :admin do
    get "", to: "login#index", as: "start" #alias for the admin start page 
    resources :employees do
      collection do
        get 'invalid'
      end
      member do
        post 'mark_as_duplicate'
      end
    end
    resources :services
    get 'duplicates', to: 'duplicates#index', as: 'duplicates'
    get 'duplicates/:primary_employee_id', to: 'duplicates#index'
    get 'duplicates/:primary_employee_id/:secondary_employee_id', to: 'duplicates#index', as: 'duplicates_primary_secondary'
  end

end

app/models/service.rb
class Service < ApplicationRecord


  # ----------
  # validations
  # ----------


 # ----------
  # associations
  # ----------
  has_many :employees
  attribute :name, :string


  # ----------
  # callbacks
  # ----------



  # ----------
  # search
  # ----------

  include PgSearch::Model
  pg_search_scope :search,
    against: [:name],
    using: {
      tsearch: { prefix: true }
    }

  # ----------
  # scopes
  # ----------

  scope :sorted_by, ->(sort_option) {
    direction = /desc$/.match?(sort_option) ? "desc" : "asc"
    services = Service.arel_table
    case sort_option.to_s
    when /^employee_updated_at_/
      with_employee_info.reorder("last_employees_update #{direction}")
    when /^service_/
      with_employee_info.reorder("LOWER(services.name) #{direction}")
    when /^staff_count_/
      with_employee_info.reorder("employee_count #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :with_service_id, ->(service_ids) {
    where(id: [*service_ids])
  }
  
  scope :with_employee_count_range, ->(range_key) {
    where(id: Service.select("services.id")
                     .joins(:employees)
                     .group("services.id")
                     .having(employee_count_condition_subquery(range_key)))
  }

  # gets employee count + last employee updated date for each service
  scope :with_employee_info, -> {
    select('services.*, COUNT(employees.id) AS employee_count, MAX(employees.updated_at) AS last_employees_update')
    .joins(:employees)
    .group('services.id')
    .having('MAX(employees.updated_at) IS NOT NULL')
    .order('last_employees_update DESC')
  }


  # gets the last updated employee date for each service
  scope :with_last_employee_update, -> {
    select('services.*, MAX(employees.updated_at) AS last_employees_update')
    .joins(:employees)
    .group('services.id')
    .having('MAX(employees.updated_at) IS NOT NULL')
    .order('last_employees_update DESC')
  }

  # gets the total number of employees for each service
  scope :with_employee_count, -> {
    select('services.*, COUNT(employees.id) AS employee_count')
    .joins(:employees)
    .group('services.id')
  }
 

  # ----------
  # filtering
  # ----------

  filterrific(
    default_filter_params: { sorted_by: "employee_updated_at_desc"  },
    available_filters: [
      :with_service_id,
      :with_employee_count_range,
      :search,
      :sorted_by,
    ]
  )

  # ----------
  # filter options
  # ----------


  def self.options_for_service
    Service.distinct.order("name ASC").pluck(:id, :name).map(&:reverse)
  end

  def self.options_for_number_of_staff
    {
      '0-5' => '0-5',
      '6-10' => '6-10',
      '10-20' => '10-20',
      '20+' => '20+'
    }
  end

  def self.employee_count_condition_subquery(range_key)
    case range_key
    when '0-5'
      "COUNT(employees.id) BETWEEN 0 AND 5"
    when '6-10'
      "COUNT(employees.id) BETWEEN 6 AND 10"
    when '10-20'
      "COUNT(employees.id) BETWEEN 11 AND 20"
    when '20+'
      "COUNT(employees.id) > 20"
    else
      "1=1"
    end
  end


  def self.options_for_sorted_by
    [
      ["Most recently staff updated", "employee_updated_at_desc"],
      ["Least recently staff updated", "employee_updated_at_asc"],
      ["Provider A-Z", "service_asc"],
      ["Provider Z-A", "service_desc"],
      ["Number of staff 0-9", "staff_count_asc"],
      ["Number of staff 9-0", "staff_count_desc"],
    ]
  end



end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController
  def index

    @filterrific = initialize_filterrific(
      Service.with_last_employee_update,
      params[:filterrific],
      persistence_id: false,
      select_options: {
        with_service_id: Service.options_for_service,
        with_employee_count_range: Service.options_for_number_of_staff,
        sorted_by: Service.options_for_sorted_by,
      },
    ) or return
    
    @services = @filterrific.find.page(params[:page]).per(20)

  end

  def show
    @service = Service.find(params[:id])
    @senco = @service.employees.where("roles @> ARRAY[?]::varchar[]", ["Designated SENCO"]).first
    @safeguarding_lead = @service.employees.where("roles @> ARRAY[?]::varchar[]", ["Designated Safeguarding Lead"]).first

    @filterrific = initialize_filterrific(
      @service.employees,
      params[:filterrific],
      persistence_id: false,
      select_options: {
        job_title: Employee.options_for_job_title,
        status: Employee.options_for_status,
        qualifications: Employee.options_for_qualifications,
        with_service_id: Service.options_for_service,
        sorted_by: Employee.options_for_sorted_by,
      },
      available_filters: [
        :job_title,
        :status,
        :qualifications,
        # :service,
        :search,
        :sorted_by
      ],
    ) or return
    
    @employees = @filterrific.find.page(params[:page]).includes(:service).per(20)
  end
  
end

app/helpers/service_helper.rb
module ServiceHelper 

  # on the frontend we can safely get the session name from the session
  def get_service_name_from_session(service_id) 
    service = session[:services].find { |service| service["id"] == service_id }
    if service
      service_name = service["name"]
    else
      service_name = "Unknown service name"
    end
  end

  # on the backend we get the service name from the database/cache
  def get_service_name_from_object(services, service_id)
    service = services.find { |service| service["id"].to_s == service_id }
    if service
      service_name = service["name"]
    else
      service_name = "Unknown service name"
    end
  end

  

end

app/views/admin/services/_filters.html.erb
<%= form_for_filterrific @filterrific do |f| %>


  <details class="filters" <%= "open" if params[:filterrific] %>>
    <summary class="filters__control" aria-expanded="false">Filter</summary>
    <div class="filters__body">

      <%= f.label :sorted_by, "Sort by", class: "visually-hidden" %>
      <%= f.select :sorted_by, @filterrific.select_options[:sorted_by], {include_blank: 'Sorted by'}, { class: "filters__select dvisually-hidden",  data: { autosubmit: true } } %>
      
      <%= f.label :service, "Provider", class: "visually-hidden" %>
      <%= f.select :with_service_id, @filterrific.select_options[:with_service_id], { include_blank: 'Filter by Provider' }, { class: "filters__select", data: { autosubmit: true }} %>

      <%= f.label :with_employee_count_range, "Number of staff", class: "visually-hidden" %>
      <%= f.select :with_employee_count_range, @filterrific.select_options[:with_employee_count_range], { include_blank: 'Filter by Number of staff' }, { class: "filters__select", data: { autosubmit: true }} %>
    </div>
  </details>


  <%= render partial: 'admin/shared/mini_search', locals: { f: f, matches: @services.total_count } %>
 
<% end %>

app/views/admin/services/_list.html.erb
<table class="table test-services">
  <thead>
    <tr>
      <th class="visually-hidden">ID</th>
      <%= sort_column_by("Provider", "service") %>
      <%= sort_column_by("Staff count", "staff_count")%>
      <%= sort_column_by("Last staff update", "employee_updated_at")%>
      <th class="visually-hidden">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |s| %>
      <tr>
        <td><span class="table__small"><%= s.id %></span></td>
        <td>
          <strong><%= link_to s[:name], admin_service_path(s) %></strong>
        </td>
        <td>
          <%= s.employees.count %>
        </td>
        <td>
          <%= s.last_employees_update.strftime("%d %b %Y") %>
        <td>
          <a href="<%= ENV["OAUTH_SERVER"] %>/admin/services/<%= s.id %>">Outpost service page</a>
        </td>
        <td>
          <%= link_to "View all records", admin_service_path(s) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/services/index.html.erb
<h1 class="page-header__title">Provider employee details</h1>
<%= render "admin/shared/shortcut-nav" %>


<%= render "filters" %>

<% if @services.present? %>
  <div class="table-holder">
    <%= render partial: 'list', locals: { services: @services } %>
  </div>
  <%= paginate @services %>
<% else %>
  <p class="no-results no-results--big">No services found</p>
<% end %>

app/views/admin/services/show.html.erb
<% content_for :header do %>

  <%# if @ofsted_item.present? %>
  <!--<div class="notice">
      <div class="notice__body">
          <p>
              This item has been marked as a duplicate
          </p>
      </div>
  </div>-->
  <%# end %>

  <%= render "admin/shared/dynamic-back-link", text: "Back to services", path: admin_services_path %>
  <h1 class="page-header__title two-thirds"><%= @service.name %></h1>
    <p><a href=href="<%= ENV["OAUTH_SERVER"] %>/admin/services/<%= @service.id %>">View service in Outpost</a></p>
   
    <p>
      <strong>SENCO:</strong> 
      <% if @senco.present? %><%= link_to employee_display_name(@senco), admin_employee_path(@senco.id)  %><% else %>
      n/a<% end %>
    </p>
    <p>
      <strong>Designated Safety Lead:</strong> 
      <% if @safeguarding_lead.present? %><%= link_to employee_display_name(@safeguarding_lead), admin_employee_path(@safeguarding_lead.id)  %><% else %>
      n/a<% end %>
    </p>

<% end %>

<%= render "admin/employees/filters" %>

<%= render partial: 'admin/employees/index', locals: { employees: @employees } %>