config/routes.rb
Rails.application.routes.draw do
  root "flow#start"

  get "start", to: "flow#start", as: "start"
  get "eligibility", to: "flow#eligibility", as: "eligibility"
  post "eligibility", to: "flow#check_eligibility"
  get "eligible", to: "flow#eligible", as: "eligible"
  get "ineligible", to: "flow#ineligible", as: "ineligible"
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  resources :employees, except: :edit

  post "finish", to: "flow#finish", as: "finish"
  post "logout", to: "sessions#destroy", as: "logout" 

  namespace :admin do
    get "", to: "login#index", as: "start" #alias for the admin start page 
    resources :employees do
      collection do
        get 'invalid'
      end
      member do
        post 'mark_as_duplicate'
      end
    end
    resources :services
    get 'duplicates', to: 'duplicates#index', as: 'duplicates'
    get 'duplicates/:primary_employee_id', to: 'duplicates#index'
    get 'duplicates/:primary_employee_id/:secondary_employee_id', to: 'duplicates#index', as: 'duplicates_primary_secondary'
  end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::BaseController
  before_action :user_admins_only!, only: [:invalid]
  before_action :set_employee, only: [:update]
  before_action :set_services, only: [:edit, :update]

  def index
    @filterrific = initialize_filterrific(
      Employee,
      params[:filterrific],
      persistence_id: false,
      select_options: {
        job_title: Employee.options_for_job_title,
        status: Employee.options_for_status,
        qualifications: Employee.options_for_qualifications,
        with_service_id: Service.options_for_service,
        sorted_by: Employee.options_for_sorted_by,
      },
    ) or return
    
    @employees = @filterrific.find.page(params[:page]).includes(:service, :duplicate).per(20)
  end

  def show
    @employee = Employee.includes(:duplicate).find(params[:id])
    if @employee.versions.length > 4
      @versions = @employee.versions.first(3)
      @versions.push(@employee.versions.last)
    else
      @versions = @employee.versions
    end

    respond_to do |format|
      format.html
      format.json { render json: @employee }
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    if @employee.versions.length > 4
      @versions = @employee.versions.first(3)
      @versions.push(@employee.versions.last)
    else
      @versions = @employee.versions
    end
  end

  def invalid
    @employees = Employee.all.includes(:service).reject(&:valid?)

    respond_to do |format|
      format.html
      format.json { render json: @employees.to_json }
    end
  end


  def update
    ActiveRecord::Base.transaction do
      update_employment_status
      update_skills
      remove_skills
      update_roles_and_qualifications
      update_employee_attributes
    end

    if @employee.save
      redirect_to admin_employee_path(@employee), notice: 'Employee updated successfully.'
    else
      render :edit
    end
  rescue => e
    Rails.logger.error "Error updating employee: #{e.message}"
    if @employee.present?
      redirect_to edit_admin_employee_path(@employee), alert: 'An error occurred while updating the employee.'
    else
      redirect_to admin_employees_path, alert: 'Employee not found.'
    end
  end

  def mark_as_duplicate
    duplicate = Duplicate.find_or_create_by(employee_id: params[:id])
    if duplicate
      duplicate.toggle!(:is_duplicate)
      redirect_back fallback_location: admin_employee_path(params[:id]), notice: "Employee updated."
    else
      redirect_back fallback_location: admin_employee_path(params[:id]), alert: 'An error occured while marking employee as duplicate.' 
    end 
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.soft_delete
    redirect_to admin_employees_path, notice: 'Employee was successfully deleted.'
  end

  
  private

  def employee_params
    params.require(:employee).permit(
      :forenames, 
      :surname, 
      :date_of_birth, 
      :street_address,
      :postal_code, 
      :service_id, 
      :employed_from, 
      :currently_employed, 
      :employed_to, 
      :job_title,
      :skills,
      :has_dbs_check,
      :dbs_achieved_on,
      :has_first_aid_training,
      :first_aid_achieved_on,
      :has_food_hygiene,
      :food_hygiene_achieved_on,
      :has_senco_training,
      :senco_achieved_on,
      :has_safeguarding,
      :safeguarding_achieved_on,
      :has_senco_early_years,
      :senco_early_years_achieved_on,
      :remove_dbs, 
      :remove_firstaid, 
      :remove_foodhygiene, 
      :remove_senco, 
      :remove_safeguarding, 
      :remove_earlyyears,
      :roles => [], 
      :qualifications => []
      )
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def update_employment_status
    if employee_params[:currently_employed] == "1"
      @employee.employed_to = nil
    end
  end

  def update_skills
    process_skills(params[:employee][:skills]) if params[:employee][:skills].present?
  end

  def remove_skills
    SKILL_REMOVAL_ATTRIBUTES.each do |flag, attrs|
      next unless employee_params[flag] == "true"
      attrs.each { |attr| @employee.send("#{attr}=", nil) }
    end
  end

  def update_roles_and_qualifications
    @employee.roles = params[:employee][:roles] || []
    @employee.qualifications = params[:employee][:qualifications] || []
  end

  def update_employee_attributes
    @employee.assign_attributes(employee_params.except(:remove_dbs, :remove_firstaid, :remove_foodhygiene, :remove_senco, :remove_earlyyears, :remove_safeguarding, :skills))
  end

  SKILL_REMOVAL_ATTRIBUTES = {
    remove_dbs: [:has_dbs_check, :dbs_achieved_on],
    remove_firstaid: [:has_first_aid_training, :first_aid_achieved_on],
    remove_foodhygiene: [:has_food_hygiene, :food_hygiene_achieved_on],
    remove_senco: [:has_senco_training, :senco_achieved_on],
    remove_safeguarding: [:has_safeguarding, :safeguarding_achieved_on],
    remove_earlyyears: [:has_senco_early_years, :senco_early_years_achieved_on]
    }.freeze

  def process_skills(skills)
    skills.each do |_, cert|
      case cert[:type]
      when 'dbs'
        @employee.has_dbs_check = true
        @employee.dbs_achieved_on = cert[:date]
      when 'first_aid'
        @employee.has_first_aid_training = true
        @employee.first_aid_achieved_on = cert[:date]
      when 'food_hygiene'
        @employee.has_food_hygiene = true
        @employee.food_hygiene_achieved_on = cert[:date]
      when 'senco'
        @employee.has_senco_training = true
        @employee.senco_achieved_on = cert[:date]
      when 'safeguarding'
        @employee.has_safeguarding = true
        @employee.safeguarding_achieved_on = cert[:date]
      when 'senco_early_years'
        @employee.has_senco_early_years = true
        @employee.senco_early_years_achieved_on = cert[:date]
      end
    end
  end

  def set_services
    @services = Service.all.collect { |s| [s.name, s.id] }
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_eligibility!
  before_action :set_employees, only: :index
  before_action :set_employee, only: [:show, :update, :destroy]

  def index
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.organisation_id = session[:organisation_id]
    if @employee.save
      redirect_to employees_path
    else
      render "new"
    end
  end

  def show
  end

  def update  
    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Employee updated successfully.'
    else
      render "show"
    end
  end

  def destroy
    if @employee.destroy
      redirect_to employees_path
    end
  end

  # helps us to track any possible service name changes when it comes to auditing
  # nb outpost has most of this data saved already, so we can use it to track changes
  def info_for_paper_trail
    get_service_name = Proc.new do 
      if params[:employee].present? && params[:employee][:service_id].present?
        service = session[:services]
        service = session[:services].find { |s| s["id"] == params[:employee][:service_id].to_i }
        if service
          service["name"]
        else
          "Unknown service name"
        end
      else
        "Unknown service name"
      end
    end

    { 
      service_name: get_service_name.call(),
      user_name: [session[:first_name], session[:last_name]].join(' '),
    }
  end

  private

  def set_employees
    @employees = Employee.where(organisation_id: session[:organisation_id])
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(
      :surname,
      :forenames,
      :street_address,
      :postal_code,
      :date_of_birth,

      :service_id,
      :job_title,
      :employed_from,
      :employed_to,
      :currently_employed,

      :has_dbs_check,
      :dbs_achieved_on,
      :has_first_aid_training,
      :first_aid_achieved_on,
      :has_food_hygiene,
      :food_hygiene_achieved_on,
      :has_senco_training,
      :senco_achieved_on,
      :has_safeguarding,
      :safeguarding_achieved_on,
      :has_senco_early_years,
      :senco_early_years_achieved_on,
      :qualifications => [],
      :roles => []
    )
  end
end

app/helpers/employee_helper.rb
module EmployeeHelper 

  def employee_display_forenames(employee) 
    if employee.forenames.nil?
      employee.forenames = 'NULL'
    end
    employee.forenames
  end

  def employee_display_surname(employee) 
    if employee.surname.nil?
      employee.surname = 'NULL'
    end
    employee.surname
  end

  def employee_display_name(employee) 
    if employee.forenames.nil?
      employee.forenames = 'NULL'
    end
    if employee.surname.nil?
      employee.surname = 'NULL'
    end
    [employee.forenames, employee.surname].join(' ')
  end

  def edit_employee_link(e, text = '')
    if admin_users?
      "<a href=\"#{edit_admin_employee_url(e)}\" class=\"icon-edit\" title=\"Edit #{employee_display_name(e)} \">#{text}<span class=\"visually-hidden\">Edit this employee</span></a>".html_safe
    end 
  end

  # Childminder, Rainbow Nursery or NULL, Rainbow Nursery
  def employee_display_job_summary(employee) 
    if employee.job_title.nil?
      employee.job_title = 'NULL'
    end

    [employee.job_title, employee.service.name].join(', ')
  end

end

app/views/employees/_form.html.erb
<%= form_for @employee, html: {class: "two-thirds"} do |f| %>


<%= render "shared/errors", model: @employee %>

 <%= render "employees/editors/personal-information", f: f %>

<div class="field-group">

<h2>About their employment</h2>

 <%= render "employees/editors/user-provider", f: f %>

 <%= render "employees/editors/job-title", f: f %>

 <%= render "employees/editors/roles", f: f %>

 <%= render "employees/editors/employment", f: f %>

</div>

<div class="field-group">

<h2>About their skills</h2>

 <%= render "employees/editors/skills", f: f %>

 <%= render "employees/editors/qualifications", f: f %>

</div>

<div class="form-actions">
  <%= f.button "Continue", class: "button", id: "submit_form" %>
</div>

<% end %>

app/views/employees/index.html.erb
<% content_for :header do %>
  <h1 class="page-header__title">Your employees</h1>
<% end %>

<% if @employees.any? %>
  <div class="table-holder">
    <table>
      <thead>
        <tr>
          <th>Surname</th>
          <th>Forenames</th>
          <th>Job title</th>
          <th>Employed at</th>
          <th>Employed from</th>
          <th>Employed to</th>
        </tr>
      </thead>
      <tbody>
        <% @employees.each do |e| %>
          <tr>
            <td><%= e.surname %></td>
            <td><%= e.forenames %></td>
            <td><%= e.job_title %></td>

            <td><%= get_service_name_from_session(e.service_id) %></td>
            <td><%= e.employed_from.strftime("%d/%m/%Y") %></td>
            <td>
              <% if e.employed_to %>
                <%= e.employed_to.strftime("%d/%m/%Y") %>
              <% else %>
                —
              <% end %>
            </td>
            <td>
              <%= link_to "Change", employee_path(e), class: "table-action" %>
              <%= link_to "Remove", employee_path(e), method: :delete, data: { confirm: "Are you sure? You should only delete records if they are mistakes. If someone leaves your organisation, add the date they left." }, class: "table-action" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to "Add new employee", new_employee_path, class: "button button--secondary button--add" %>
<% else %>
  <%= link_to "Add your first employee", new_employee_path, class: "button button--secondary button--add" %>
<% end %>


<%= form_tag finish_path do %>
  <h2>Ready to continue?</h2>

  <p>If these records are accurate, carry on.</p>

  <div class="field checkbox">
    <%= check_box_tag :confirm_validity, true, false, class: "checkbox__input", required: true %>
    <%= label_tag :confirm_validity, "These records are complete to the best of my knowledge", class: "checkbox__label" %>
  </div>
  <div class="form-actions">
    <%= button_tag "Finish and send", class: "button" %>
  </div>
<% end %>

app/views/employees/new.html.erb
<% content_for :header do %>
    <%= link_to "Back to list", employees_path, class: "go-back" %>
    <h1 class="page-header__title">Add a new employee</h1>
<% end %>

<%= render "form" %>

app/views/employees/show.html.erb
<% content_for :header do %>
    <%= link_to "Back to list", employees_path, class: "go-back" %>
    <h1 class="page-header__title">Edit an employee</h1>
<% end %>

<%= render "form" %>