config/routes.rb
Rails.application.routes.draw do
  root "flow#start"

  get "start", to: "flow#start", as: "start"
  get "eligibility", to: "flow#eligibility", as: "eligibility"
  post "eligibility", to: "flow#check_eligibility"
  get "eligible", to: "flow#eligible", as: "eligible"
  get "ineligible", to: "flow#ineligible", as: "ineligible"
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  resources :employees, except: :edit

  post "finish", to: "flow#finish", as: "finish"
  post "logout", to: "sessions#destroy", as: "logout" 

  namespace :admin do
    get "", to: "login#index", as: "start" #alias for the admin start page 
    resources :employees do
      collection do
        get 'invalid'
      end
      member do
        post 'mark_as_duplicate'
      end
    end
    resources :services
    get 'duplicates', to: 'duplicates#index', as: 'duplicates'
    get 'duplicates/:primary_employee_id', to: 'duplicates#index'
    get 'duplicates/:primary_employee_id/:secondary_employee_id', to: 'duplicates#index', as: 'duplicates_primary_secondary'
  end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::BaseController
  before_action :user_admins_only!, only: [:invalid]
  before_action :set_employee, only: [:update]
  before_action :set_services, only: [:edit, :update]

  def index
    @filterrific = initialize_filterrific(
      Employee,
      params[:filterrific],
      persistence_id: false,
      select_options: {
        job_title: Employee.options_for_job_title,
        status: Employee.options_for_status,
        qualifications: Employee.options_for_qualifications,
        with_service_id: Service.options_for_service,
        sorted_by: Employee.options_for_sorted_by,
      },
    ) or return
    
    @employees = @filterrific.find.page(params[:page]).includes(:service, :duplicate).per(20)
  end

  def show
    @employee = Employee.includes(:duplicate).find(params[:id])
    if @employee.versions.length > 4
      @versions = @employee.versions.first(3)
      @versions.push(@employee.versions.last)
    else
      @versions = @employee.versions
    end

    respond_to do |format|
      format.html
      format.json { render json: @employee }
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    if @employee.versions.length > 4
      @versions = @employee.versions.first(3)
      @versions.push(@employee.versions.last)
    else
      @versions = @employee.versions
    end
  end

  def invalid
    @employees = Employee.all.includes(:service).reject(&:valid?)

    respond_to do |format|
      format.html
      format.json { render json: @employees.to_json }
    end
  end


  def update
    ActiveRecord::Base.transaction do
      update_employment_status
      update_skills
      remove_skills
      update_roles_and_qualifications
      update_employee_attributes
    end

    if @employee.save
      redirect_to admin_employee_path(@employee), notice: 'Employee updated successfully.'
    else
      render :edit
    end
  rescue => e
    Rails.logger.error "Error updating employee: #{e.message}"
    if @employee.present?
      redirect_to edit_admin_employee_path(@employee), alert: 'An error occurred while updating the employee.'
    else
      redirect_to admin_employees_path, alert: 'Employee not found.'
    end
  end

  def mark_as_duplicate
    duplicate = Duplicate.find_or_create_by(employee_id: params[:id])
    if duplicate
      duplicate.toggle!(:is_duplicate)
      redirect_back fallback_location: admin_employee_path(params[:id]), notice: "Employee updated."
    else
      redirect_back fallback_location: admin_employee_path(params[:id]), alert: 'An error occured while marking employee as duplicate.' 
    end 
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.soft_delete
    redirect_to admin_employees_path, notice: 'Employee was successfully deleted.'
  end

  
  private

  def employee_params
    params.require(:employee).permit(
      :forenames, 
      :surname, 
      :date_of_birth, 
      :street_address,
      :postal_code, 
      :service_id, 
      :employed_from, 
      :currently_employed, 
      :employed_to, 
      :job_title,
      :skills,
      :has_dbs_check,
      :dbs_achieved_on,
      :has_first_aid_training,
      :first_aid_achieved_on,
      :has_food_hygiene,
      :food_hygiene_achieved_on,
      :has_senco_training,
      :senco_achieved_on,
      :has_safeguarding,
      :safeguarding_achieved_on,
      :has_senco_early_years,
      :senco_early_years_achieved_on,
      :remove_dbs, 
      :remove_firstaid, 
      :remove_foodhygiene, 
      :remove_senco, 
      :remove_safeguarding, 
      :remove_earlyyears,
      :roles => [], 
      :qualifications => []
      )
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def update_employment_status
    if employee_params[:currently_employed] == "1"
      @employee.employed_to = nil
    end
  end

  def update_skills
    process_skills(params[:employee][:skills]) if params[:employee][:skills].present?
  end

  def remove_skills
    SKILL_REMOVAL_ATTRIBUTES.each do |flag, attrs|
      next unless employee_params[flag] == "true"
      attrs.each { |attr| @employee.send("#{attr}=", nil) }
    end
  end

  def update_roles_and_qualifications
    @employee.roles = params[:employee][:roles] || []
    @employee.qualifications = params[:employee][:qualifications] || []
  end

  def update_employee_attributes
    @employee.assign_attributes(employee_params.except(:remove_dbs, :remove_firstaid, :remove_foodhygiene, :remove_senco, :remove_earlyyears, :remove_safeguarding, :skills))
  end

  SKILL_REMOVAL_ATTRIBUTES = {
    remove_dbs: [:has_dbs_check, :dbs_achieved_on],
    remove_firstaid: [:has_first_aid_training, :first_aid_achieved_on],
    remove_foodhygiene: [:has_food_hygiene, :food_hygiene_achieved_on],
    remove_senco: [:has_senco_training, :senco_achieved_on],
    remove_safeguarding: [:has_safeguarding, :safeguarding_achieved_on],
    remove_earlyyears: [:has_senco_early_years, :senco_early_years_achieved_on]
    }.freeze

  def process_skills(skills)
    skills.each do |_, cert|
      case cert[:type]
      when 'dbs'
        @employee.has_dbs_check = true
        @employee.dbs_achieved_on = cert[:date]
      when 'first_aid'
        @employee.has_first_aid_training = true
        @employee.first_aid_achieved_on = cert[:date]
      when 'food_hygiene'
        @employee.has_food_hygiene = true
        @employee.food_hygiene_achieved_on = cert[:date]
      when 'senco'
        @employee.has_senco_training = true
        @employee.senco_achieved_on = cert[:date]
      when 'safeguarding'
        @employee.has_safeguarding = true
        @employee.safeguarding_achieved_on = cert[:date]
      when 'senco_early_years'
        @employee.has_senco_early_years = true
        @employee.senco_early_years_achieved_on = cert[:date]
      end
    end
  end

  def set_services
    @services = Service.all.collect { |s| [s.name, s.id] }
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_eligibility!
  before_action :set_employees, only: :index
  before_action :set_employee, only: [:show, :update, :destroy]

  def index
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.organisation_id = session[:organisation_id]
    if @employee.save
      redirect_to employees_path
    else
      render "new"
    end
  end

  def show
  end

  def update  
    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Employee updated successfully.'
    else
      render "show"
    end
  end

  def destroy
    if @employee.destroy
      redirect_to employees_path
    end
  end

  # helps us to track any possible service name changes when it comes to auditing
  # nb outpost has most of this data saved already, so we can use it to track changes
  def info_for_paper_trail
    get_service_name = Proc.new do 
      if params[:employee].present? && params[:employee][:service_id].present?
        service = session[:services]
        service = session[:services].find { |s| s["id"] == params[:employee][:service_id].to_i }
        if service
          service["name"]
        else
          "Unknown service name"
        end
      else
        "Unknown service name"
      end
    end

    { 
      service_name: get_service_name.call(),
      user_name: [session[:first_name], session[:last_name]].join(' '),
    }
  end

  private

  def set_employees
    @employees = Employee.where(organisation_id: session[:organisation_id])
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(
      :surname,
      :forenames,
      :street_address,
      :postal_code,
      :date_of_birth,

      :service_id,
      :job_title,
      :employed_from,
      :employed_to,
      :currently_employed,

      :has_dbs_check,
      :dbs_achieved_on,
      :has_first_aid_training,
      :first_aid_achieved_on,
      :has_food_hygiene,
      :food_hygiene_achieved_on,
      :has_senco_training,
      :senco_achieved_on,
      :has_safeguarding,
      :safeguarding_achieved_on,
      :has_senco_early_years,
      :senco_early_years_achieved_on,
      :qualifications => [],
      :roles => []
    )
  end
end

app/helpers/employee_helper.rb
module EmployeeHelper 

  def employee_display_forenames(employee) 
    if employee.forenames.nil?
      employee.forenames = 'NULL'
    end
    employee.forenames
  end

  def employee_display_surname(employee) 
    if employee.surname.nil?
      employee.surname = 'NULL'
    end
    employee.surname
  end

  def employee_display_name(employee) 
    if employee.forenames.nil?
      employee.forenames = 'NULL'
    end
    if employee.surname.nil?
      employee.surname = 'NULL'
    end
    [employee.forenames, employee.surname].join(' ')
  end

  def edit_employee_link(e, text = '')
    if admin_users?
      "<a href=\"#{edit_admin_employee_url(e)}\" class=\"icon-edit\" title=\"Edit #{employee_display_name(e)} \">#{text}<span class=\"visually-hidden\">Edit this employee</span></a>".html_safe
    end 
  end

  # Childminder, Rainbow Nursery or NULL, Rainbow Nursery
  def employee_display_job_summary(employee) 
    if employee.job_title.nil?
      employee.job_title = 'NULL'
    end

    [employee.job_title, employee.service.name].join(', ')
  end

end

app/views/admin/employees/_employees.html.erb
<% if @employees.present? %>
<table class="table-holder">
  <thead>
    <tr>
      <th>
        <% sort_direction = params[:direction] == 'asc' && params[:sort] == 'forenames' ? 'desc' : 'asc' %>
        <%= link_to admin_employees_path(sort: 'forenames', direction: sort_direction) do %>
          First names
          <%= image_tag sort_direction == 'asc' ? "down-arrow.svg" : "up-arrow.svg", 
                      alt: "Sort by Forenames", 
                      class: "sorting-icon" %>
        <% end %>
      </th>
            <th>
        <% sort_direction = params[:direction] == 'asc' && params[:sort] == 'surname' ? 'desc' : 'asc' %>
        <%= link_to admin_employees_path(sort: 'surname', direction: sort_direction) do %>
          Surname
          <%= image_tag sort_direction == 'asc' ? "down-arrow.svg" : "up-arrow.svg", 
                      alt: "Sort by Surname", 
                      class: "sorting-icon" %>
        <% end %>
      </th>
            <th>
        <% sort_direction = params[:direction] == 'asc' && params[:sort] == 'job_title' ? 'desc' : 'asc' %>
        <%= link_to admin_employees_path(sort: 'job_title', direction: sort_direction) do %>
          Job title
          <%= image_tag sort_direction == 'asc' ? "down-arrow.svg" : "up-arrow.svg", 
                      alt: "Sort by Job title", 
                      class: "sorting-icon" %>
        <% end %>
      </th> 
      <th><a>Provider<%= image_tag "down-arrow.svg", alt: "Sort by Provider", class: "sorting-icon" %></a></th>
      <th><a>Qualifications<%= image_tag "down-arrow.svg", alt: "Sort by Qualifications", class: "sorting-icon" %></a></th>
      <th><a>Status<%= image_tag "down-arrow.svg", alt: "Sort by Status", class: "sorting-icon" %></a></th>
    </tr>
  </thead>
  <tbody>
  <% @employees.each do |employee| %>
    <tr>
      <td>
        <strong>
          <%= link_to employee.forenames, admin_employee_path(employee) %>
        </strong>
        <button class="mini-search__submit">
        <%= image_tag "search.svg", alt: "Submit search" %>
        </button>
      </td>
      <td><%= employee.surname %></td>
      <td><%= employee.job_title %></td>
      <td><%= service_name_by_id(employee.service_id) %></td>
      <td>
      <% if employee.qualifications.present? %>
        <% employee.qualifications.each do |qualification| %>
          <%= qualification %>
        <% end %>
      <% else %>
        No qualifications
      <% end %>
      </td>
      <td class="tag margin-top--md <%= employee.currently_employed? ? 'bg--active color--active border--active' : 'bg--inactive color--inactive border--inactive' %>">
        <%= employee.currently_employed? ? 'Active' : 'Inactive' %>
      </td>
    </tr>
  <% end %> 
  </tbody>
</table>

<% else %>
      <div>
        <h1>No employees found</td>
      </div>
    <% end %>

app/views/admin/employees/_index.html.erb
<% if @employees.present? %>
  <div class="table-holder">
    <%= render partial: 'admin/employees/list', locals: { employees: @employees } %>
  </div>
  <%= paginate @employees %>
<% else %>
  <p class="no-results no-results--big">No employees found</p>
<% end %>

app/views/admin/employees/_list.html.erb
<table class="table test-employees">
  <caption>
    A list of all employees entered into the system
    <span class="sr-only">, column headers with buttons are sortable.</span>
  </caption>
  <thead>
    <tr>
      <!--<th class="visually-hidden">ID</th>-->
      <%= sort_column_by("Forenames", "forenames") %>
      <%= sort_column_by("Surame", "surname") %>
      <%= sort_column_by("Job title", "job_title") %>
      <%= sort_column_by("Provider", "service") %>
      <th>Qualifications</th>
      <%= sort_column_by("Status", "status") %>
      <th class="visually-hidden">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |e| %>
      <tr>
        <!--<td><span class="table__small"><%= e.id %></span></td>-->
        <td>
            <strong><%= link_to employee_display_forenames(e).truncate(30), admin_employee_path(e), title: employee_display_forenames(e) %></strong>
        </td>
        <td>
            <%= link_to employee_display_surname(e).truncate(30), admin_employee_path(e), title: employee_display_surname(e) %>
        </td>
        <td>
          <%= e.job_title %>
        </td>
        <td>
            <%= link_to e.service.name.truncate(30), admin_service_path(e.service.id), title: e.service.name %>
        </td>
        <td>
          <%= safe_join(e.qualifications, tag(:br)) if e.qualifications.present? %>
        </td>
        <td>
          <%= status_tag(e.currently_employed? ? 'Active' : 'Inactive') %>
        </td>
        <td>
        <div class="actions-inline">
          <%= edit_employee_link(e) %>
          <%= flag_duplicate_link(e) %>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/employees/edit.html.erb
<% content_for :header do %>

  <% if @employee.duplicate && @employee.duplicate.is_duplicate %>
      <div class="notice">
        <div class="notice__body">
          <p>
            This item has been marked as a potential duplicate of another record. 
          </p>
          <p>
          To merge or delete records please go to the <%= link_to 'duplicates page', admin_duplicates_path %>.
          </p>
        </div>
      </div>
  <% end %>  

  <%= render "admin/shared/dynamic-back-link", text: "Back to view provider employee details", path: admin_employee_path(@employee) %>
  <h1 class="page-header__title two-thirds"><%= employee_display_name(@employee) %></h1>
  <h2><%= employee_display_job_summary(@employee) %></h2>
  <p class="text-light">Record <%= @employee.id %>  </p>
<% end %>


<header class="actions">
  <% if admin_users? %><%= link_to 'View', admin_employee_path(@employee), class: 'inline-button button--secondary' %>  <% end %>
  <button class="inline-button actions__pull-right" data-open-all>Open all</button>
  <button class="inline-button" data-close-all>Close all</button>
</header>

<div class="with-sidebar">

  <div>
    <%= form_for([:admin, @employee]) do |f| %>

    <%= render "shared/errors", model: @employee %>


    <%= render "admin/shared/collapsible", name: "Personal information", id: "employee-personal-information" do %>
      <%= render "employees/editors/personal-information", f: f %>
    <% end %>



    <%= render "admin/shared/collapsible", name: "Provider", id: "employee-provider-information" do %>
      <%= render "admin/employees/editors/provider", f: f %>
      <%= render "employees/editors/employment", f: f %>
    <% end %>


    <%= render "admin/shared/collapsible", name: "Job title", id: "employee-job-title" do %>
      <%= render "employees/editors/job-title", f: f %>
    <% end %>


    <%= render "admin/shared/collapsible", name: "Roles", id: "employee-roles" do %>
      <%= render "employees/editors/roles", f: f %>
    <% end %>


    <%= render "admin/shared/collapsible", name: "Skills", id: "employee-skills" do %>
        <%= render "employees/editors/skills", f: f %>
    <% end %>
    


    <%= render "admin/shared/collapsible", name: "Qualifications", id: "employee-qualifications" do %>
      <%= render "employees/editors/qualifications", f: f %>
    <% end %>


      <div class="form-actions">
          <%= f.submit "Save", class: "button" %>
          <%= link_to 'Cancel', admin_employees_path %>
      </div>

        <% end %>
    


    <% if admin_users? %>
      <div class="danger-zone">
          <h2>Danger zone</h2>
          <p>Permanently deleted employees will be removed after 30 days. They can't be recovered by anyone.</p>
          <%= link_to 'Delete employee', admin_employee_path(@employee), class: 'button button--danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

  </div>

  <aside class="with-sidebar__sidebar">
    <%= render "admin/shared/collapsible", name: "Status", id: "employee-status" do %>
      <%= render "admin/employees/data/status", object: @employee %>
    <% end %>

    <%= render "admin/shared/collapsible", name: "History", id: "employee-history" do %>
      <%= render "admin/employees/data/history", object: @employee %>
    <% end %>

    <%= render "admin/shared/collapsible", name: "Duplicate", id: "employee-duplicate" do %>  
    <strong>
      <%= flag_duplicate_link(@employee, @employee.duplicate && @employee.duplicate.is_duplicate ? "Mark as not a duplicate" : "Mark as a duplicate") %>
    </strong>
    <% end %>

  </aside>

</div>

app/views/admin/employees/index.html.erb
<h1 class="page-header__title">Provider employee details</h1>
<%= render "admin/shared/shortcut-nav" %>
<%= render "filters" %>
<%= render partial: 'index', locals: { employees: @employees } %>

app/views/admin/employees/invalid.html.erb
<h1 class="page-header__title">Invalid employees</h1>
<p>Certain employees from previous versions of the system have been marked as invalid. This is because they are missing required information. 
Please review the list below and we can update the records as necessary.</p>
<p><%= link_to 'Download as json', invalid_admin_employees_path(:format => :json) %></p>


<% if @employees.present? %>
<div class="table-holder">
  <table class="table test-employees">
    <caption>
      A list of all invalid employees 
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Provider</th>
        <th>Created</th>
        <th>Updated</th>
        <th>Error</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |e| %>
      <% if not e.valid? %>
        <tr>
          <td><span class="table__small"><%= e.id %></span></td>
          <td>
              <strong><%= link_to e.forenames, admin_employee_path(e) %></strong>
          </td>
          <td>
            <%= link_to e.surname, admin_employee_path(e), title: e.surname %>
          </td>
          <td>
              <%= link_to e.service.name.truncate(30), admin_service_path(e.service.id), title: e.service.name %>
          </td>
          <td>
              <%= e.created_at.strftime("%d-%m-%Y %H:%M:%S") %>
          </td>
          <td>
              <%= e.updated_at.strftime("%d-%m-%Y %H:%M:%S") %>
          </td>
          <td>
            <%= e.errors.full_messages.to_sentence %>
          </td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<%#= paginate @employees %>
<% else %>
  <p class="no-results no-results--big">No invalid employees found</p>
<% end %>

app/views/admin/employees/show.html.erb
<% content_for :header do %>


  <% if @employee.duplicate && @employee.duplicate.is_duplicate %>
      <div class="notice">
        <div class="notice__body">
          <p>
            This item has been marked as a potential duplicate of another record. 
          </p>
          <p>
          To merge or delete records please go to the <%= link_to 'duplicates page', admin_duplicates_path %>.
          </p>
        </div>
      </div>
  <% end %>  

  <%= render "admin/shared/dynamic-back-link", text: "Back to provider employee details", path: admin_employees_path %>
  <h1 class="page-header__title two-thirds"><%= employee_display_name(@employee) %></h1>
  <h2><%= employee_display_job_summary(@employee) %></h2>
  <p class="text-light">Record <%= @employee.id %>  </p>
<% end %>


<header class="actions">
  <% if admin_users? %><%= link_to 'Edit', edit_admin_employee_path(@employee), class: 'inline-button button--secondary' %>  <% end %>
  <button class="inline-button actions__pull-right" data-open-all>Open all</button>
  <button class="inline-button" data-close-all>Close all</button>
</header>


<div class="with-sidebar">

  <div>

    <%= render "admin/shared/collapsible", name: "Personal information", id: "employee-personal-information" do %>
      <%= render "admin/shared/field-static", label: "Forenames" do %>
        <%= employee_display_forenames(@employee) %>
      <% end %> 
      <%= render "admin/shared/field-static", label: "Surname" do %>
        <%= employee_display_surname(@employee) %>
      <% end %> 
      <%= render "admin/shared/field-static", label: "Date of birth" do %>
        <%= @employee.date_of_birth.strftime("%d/%m/%Y") unless @employee.date_of_birth.nil? %>
      <% end %> 
      <%= render "admin/shared/field-static", label: "Home address" do %>
        <%= @employee.street_address unless @employee.street_address.nil? %>
      <% end %> 
      <%= render "admin/shared/field-static", label: "Postcode" do %>
        <%= @employee.postal_code unless @employee.postal_code.nil? %>
      <% end %> 
    <% end %>



    <%= render "admin/shared/collapsible", name: "Provider", id: "employee-provider-information" do %>
      <%= render "admin/shared/field-static", label: "Current provider" do %>
        <%= link_to service_name_by_id(@employee.service_id), admin_service_path(@employee.service_id) %>
      <% end %> 
      <%= render "admin/shared/field-static", label: "Employed from" do %>
        <%= @employee.employed_from.strftime("%d/%m/%Y") unless @employee.employed_from.nil?  %>
      <% end %> 
      <%= render "admin/shared/field-static", label: "Currently employed" do %>
        <%= @employee.currently_employed? ? 'Yes' : 'No' %>
      <% end %> 
      <% if @employee.employed_to.present? %>
        <%= render "admin/shared/field-static", label: "Employed to" do %>
          <%= @employee.employed_to.strftime("%d/%m/%Y") unless @employee.employed_to.nil?  %>
        <% end %> 
      <% end %> 
    <% end %>


    <%= render "admin/shared/collapsible", name: "Job title", id: "employee-job-title" do %>
      <%= render "admin/shared/field-static", label: "Job title" do %>
        <%= @employee.job_title unless @employee.job_title.nil? %>
      <% end %> 
    <% end %>


    <%= render "admin/shared/collapsible", name: "Roles", id: "employee-roles" do %>
      <%= render "admin/shared/field-static", label: "Current roles" do %>
            <% if @employee.roles.present? %>
                <% @employee.roles.each do |role| %>
                  <%= role %><br>
                <% end %>
              <% else %>
                No roles
              <% end %>
      <% end %> 
    <% end %>


    <%= render "admin/shared/collapsible", name: "Skills", id: "employee-skills" do %>
    <% if 
        [@employee.has_dbs_check,
        @employee.has_first_aid_training,
        @employee.has_food_hygiene,
        @employee.has_senco_training,
        @employee.has_safeguarding,
        @employee.has_senco_early_years].any? %>
        <table class="table--employee-info">
          <tr class="table-column">
            <th>Skill</th>
            <th>Date achieved</th>
          </tr>
          <% if @employee.has_dbs_check %>
            <tr class="table-column">
              <td>DBS check</td>
              <td><%= @employee.dbs_achieved_on.strftime("%d/%m/%Y") %></td>
            </tr>
          <% end %>
          <% if @employee.has_first_aid_training %>
            <tr class="table-column">
              <td>Paediatric First Aid training</td>
              <td><%= @employee.first_aid_achieved_on.strftime("%d/%m/%Y") %></td>
            </tr>
          <% end %>
          <% if @employee.has_food_hygiene %>
            <tr class="table-column">
              <td>Food Hygiene Qualification</td>
              <td><%= @employee.food_hygiene_achieved_on.strftime("%d/%m/%Y") %></td>
            </tr>
          <% end %>
            <% if @employee.has_senco_training %>
            <tr class="table-column">
              <td>SENCO training</td>
              <td><%= @employee.senco_achieved_on.strftime("%d/%m/%Y") %></td>
            </tr>
          <% end %>
            <% if @employee.has_safeguarding %>
            <tr class="table-column">
              <td>(Other Safeguarding) Safeguarding for all training</td>
              <td><%= @employee.safeguarding_achieved_on.strftime("%d/%m/%Y") %></td>
            </tr>
          <% end %>
          <% if @employee.has_senco_early_years %>
            <tr class="table-column">
              <td>Early Years Level 3 SENCO</td>
              <td><%= @employee.senco_early_years_achieved_on.strftime("%d/%m/%Y") %></td>
            </tr>
          <% end %>
        </table>
          <% else %>
            <p>No skills added</p>
          <% end %>
    <% end %>
    


    <%= render "admin/shared/collapsible", name: "Qualifications", id: "employee-qualifications" do %>
     <% if @employee.qualifications.present? %>
        <table class="table--employee-info">
          <tr class="table-column">
            <th>Qualification</th>
          </tr>
        <% @employee.qualifications.each do |qualification| %>
         <tr class="table-column">
              <td><%= qualification %></td>
            </tr>
        <% end %>
        </table>
      <% else %>
        <p>No qualifications added</p>
      <% end %>
    <% end %>
    


    <% if admin_users? %>
      <div class="danger-zone">
          <h2>Danger zone</h2>
          <p>Permanently deleted employees will be removed after 30 days. They can't be recovered by anyone.</p>
          <%= link_to 'Delete employee', admin_employee_path(@employee), class: 'button button--danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

  </div>

  <aside class="with-sidebar__sidebar">
    <%= render "admin/shared/collapsible", name: "Status", id: "employee-status" do %>
      <%= render "admin/employees/data/status", object: @employee %>
    <% end %>

    <%= render "admin/shared/collapsible", name: "History", id: "employee-history" do %>
      <%= render "admin/employees/data/history", object: @employee %>
    <% end %>

    <%= render "admin/shared/collapsible", name: "Duplicate", id: "employee-duplicate" do %>  
    <strong>
      <%= flag_duplicate_link(@employee, @employee.duplicate && @employee.duplicate.is_duplicate ? "Mark as not a duplicate" : "Mark as a duplicate") %>
    </strong>
    <% end %>


    
  </aside>

</div>