config/routes.rb
Rails.application.routes.draw do
  root "flow#start"

  get "start", to: "flow#start", as: "start"
  get "eligibility", to: "flow#eligibility", as: "eligibility"
  post "eligibility", to: "flow#check_eligibility"
  get "eligible", to: "flow#eligible", as: "eligible"
  get "ineligible", to: "flow#ineligible", as: "ineligible"
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  resources :employees, except: :edit

  post "finish", to: "flow#finish", as: "finish"
  post "logout", to: "sessions#destroy", as: "logout" 

  namespace :admin do
    get "", to: "login#index", as: "start" #alias for the admin start page 
    resources :employees do
      collection do
        get 'invalid'
      end
      member do
        post 'mark_as_duplicate'
      end
    end
    resources :services
    get 'duplicates', to: 'duplicates#index', as: 'duplicates'
    get 'duplicates/:primary_employee_id', to: 'duplicates#index'
    get 'duplicates/:primary_employee_id/:secondary_employee_id', to: 'duplicates#index', as: 'duplicates_primary_secondary'
  end

end

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
    <div class="error">
        <h2 class="error__title"><%= pluralize(model.errors.count, "error") %> stopped this <%= model.class.model_name.human.downcase %> being saved</h2>
        <ul class="error__list">
            <% model.errors.full_messages.each do |e| %>
                <li><%= e.html_safe %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="site-footer">
  <div class="container">

    <nav class="site-footer__menu">
      <a class="site-footer__link" href="https://www.buckinghamshire.gov.uk/about/">About</a>
      <a class="site-footer__link" href="https://www.buckinghamshire.gov.uk/about/accessibility/">Accessibility</a>
      <a class="site-footer__link" href="https://www.buckinghamshire.gov.uk/about/cookies/">Cookies</a>
      <a class="site-footer__link" href="https://www.buckinghamshire.gov.uk/your-council/contact-us/">Contact us</a>
      <a class="site-footer__link" href="https://www.buckinghamshire.gov.uk/community-and-safety/modern-slavery-statement/">Modern slavery statement</a>
      <a class="site-footer__link" href="https://jobs.buckinghamshire.gov.uk/">Jobs</a>
      <a class="site-footer__link" href="https://www.buckinghamshire.gov.uk/coronavirus/martin-tett-coronavirus-update/subscribe-our-newsletter/">Newsletter</a>
      <%= link_to 'Admin', admin_start_path, class: 'site-footer__link' %>
    </nav>

    <p class="site-footer__license">
    <%= image_tag "ogl.svg" %>
    All content is available under the <%= link_to "Open Government Licence v.30", "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" %>, except where otherwise stated
    </p>

    <p class="site-footer__copyright">© <%= Date.current.year %> Buckinghamshire Council</p>

  </div>
</footer>

app/views/shared/_header.html.erb
<header class="site-header  <%= "site-header--logged-out" unless user_signed_in? %>">
  <div class="container site-header__inner">
    <div class="site-header__masthead">
      <%= link_to image_tag("logo.svg", alt: "Buckinghamshire Council", class: "site-header__logo"), "https://buckinghamshire.gov.uk", class: "site-header__logo-link" %>
    </div>
  
    <nav class="site-header__service-name-holder">
      <%= link_to "Tell us who you employ", root_path, class: "site-header__service-name"%>
      <span class="site-header__phase-tag">Beta</span>
    </nav>

    
    <div class="site-header__actions">
        <% if admin? %> 
          <%= link_to user_session_display_name, user_outpost_profile, class: "site-header__username"%>
          <%= link_to "Sign out", logout_path, method: :post, class: "site-header__link" %>
        <% else %> 
        <span class="site-header__username"><%= user_session_display_name %></span>
        <% end %>
    </div>
    

  </div>
</header>

app/views/shared/_navigation.html.erb
<% if user_signed_in? && admin? %>
    <nav class="site-nav">
        <div class="site-nav__inner container">

            <%= link_to_unless_current "Employees", admin_employees_path, class: "site-nav__link" do %>
                <span class="site-nav__current">Employees</span>
            <% end %>

            <%= link_to_unless_current "Services", admin_services_path, class: "site-nav__link" do %>
                <span class="site-nav__current">Services</span>
            <% end %>

            <%= link_to_unless_current "Duplicates", admin_duplicates_path, class: "site-nav__link" do %>
                <span class="site-nav__current">Duplicates</span>
            <% end %>

            <div class="site-nav__pull-right">
                <a href="<%= ENV['OAUTH_SERVER'] %>" class="site-nav__link" target="_blank">Outpost</a>
            </div>
                                
        </div>
    </nav>
<% end %>